version: '3.1'

services:
  db:
    image: postgres:13
    container_name: postgres-dev-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_PASSWORD: postgres