version: '3.1'

services:
  db:
    image: postgres:13
    container_name: postgres-development-database
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development