name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15'
      - name: Install dependencies
        run: |
          npm ci
          npm install -g dotenv-cli
      - name: Run tests
        run: |
          npm run db:up
          npm run test:coverage
          npm run db:down

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}